name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - main # Optional: Trigger on pull requests to 'main'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    # Install Hugo theme dependencies (if applicable)
    - name: Install Hugo theme dependencies
      run: |
        git submodule update --init --recursive

    # Build the Hugo site
    - name: Build site
      run: |
        hugo --minify

    # Add CNAME file
    - name: Add CNAME file
      run: |
        echo "codecrumbs.cloud" > ./public/CNAME
    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PAGES }}
        publish_dir: ./public
        publish_branch: gh-pages
